### ISSUE TITLE
Failed to load image

### ISSUE THREAD

**Issue by vanandjiwala** [charlesw/tesseract-samples#5]
I am using the sample code provided in a console application. For some sample files, i am able to get the results printed while in some case it throws an exception. I tried to see the difference between the working and non working images but the meta data seems very similar. 

I am using magick.net library with ghost script to convert PDF to TIF/PNG. I use those images in the tesseract engine to validate the results. 

` using (var img = Pix.LoadFromFile(testImagePath))` : Line 26

Exception: 
System.IO.IOException: Failed to load image '<PATH>\Snakeware.Page1.tif'.
   at Tesseract.Pix.LoadFromFile(String filename)
   at ConsoleApp3.utils.Ocr.performOCR() in <PATH>\Ocr.cs:line 26

**Comment by devrodmastria** [comment]
Try including the full path name, and using double quotes, like this:
var testImagePath = "C:\\\Users\\\\...";
Also, simplify the file name, so use "SnakewarePage1" instead of "Snakeware.Page1"

**Comment by PoojaKamra** [comment]
I am also getting the same issue with old jpeg compressed tif images.
Please help

**Comment by mjung8** [comment]
image Properties > Copy to Output Directory: Copy always
